struct PaddingItem {
  top-bottom:length,
  left-right:length,
  same:length
}

enum PaddingSize{
  None,
  Tip,
  Icon,
  Tag,
  Small,
  Normal,
  Large
}


struct ThemePadding {
  none:PaddingItem,
  tip:PaddingItem,
  tag:PaddingItem,
  icon:PaddingItem,
  small: PaddingItem,
  normal:PaddingItem,
  large:PaddingItem
}

enum Borders{
  None,
  Small,
  Normal,
  Large,
  X-Large,
  Circle-None,
  Circle-Small,
  Circle-Normal,
  Circle-Large,
  Circle-X-Large,
}

struct BorderItem {
  border-radius:length,
  border-width:length
}

struct ThemeBorder {
    none:BorderItem,
    small:BorderItem,
    normal:BorderItem,
    large:BorderItem,
    x-large:BorderItem,
    circle:{
      none:BorderItem,
      small:BorderItem,
      normal:BorderItem,
      large:BorderItem,
      x-large:BorderItem,
    }
}

export { 
  ThemePadding,ThemeBorder,PaddingSize,PaddingItem,Borders,BorderItem
}

