/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230907
* @version:0.0.1
* @type:interface
* @description:
* # SHeader
* SHeader is a simple header component that is generated based on routing information
* ## properties
* - in property <length> spacing : spacing of the header ⛔
* - in property <Route> route : detail routes , like:`{home:"Surrealism",routes:["user","info"]};`
* - in property <length> font-size : font size
* ## functions
* ## callbacks
* - callback to(int,string) : to page (it depends on you)
* - callback back() : back to main page (it depends on you)
* ============================================
*/
import {ROOT_STYLES,Themes,IconSources} from "../../themes/index.slint";
import { SIcon } from "../icon/index.slint";
import { SText } from "../text/index.slint";
import { SCard } from "../card/index.slint";
import {SHeaderNode,DefaultSHeaderProps} from "../../use/index.slint";

export component Header inherits SCard { 
  width: 100%;
  card-height: ROOT-STYLES.sur-font.font-size;
  in property <length> spacing : DefaultSHeaderProps.spacing;
  in property <[SHeaderNode]> value : DefaultSHeaderProps.value;
  in property <length> font-size : ROOT-STYLES.sur-font.font-size;
  in property <image> source :IconSources.icons.Right;
  callback clicked(int,SHeaderNode);
  HorizontalLayout {
    padding-left: parent.padding-left;
    padding-right: parent.padding-right;
    spacing: root.spacing;
    for item[index] in root.value: TouchArea{
      z: 20;
      mouse-cursor: pointer;
      clicked => {
        root.clicked(index,item);
      }
      HorizontalLayout {
        icon-view:=Rectangle{
          width: icon.width;
          icon:=SIcon{
            height: font-size;
            width: font-size;
            theme: root.theme;
            source: root.source;  
          }
        }
        txt-view:=Rectangle{
          width: txt.width;
          txt:=SText{ 
            theme: root.theme;
            text: item.label;
            font-size: root.font-size;
          }
        }
      }
    }
  }
}