/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230905
* @version:0.0.1
* @description: global font family import file
* ============================================
*/


//default font family is "Arial"
// # Arial 
// Arial 是 Microsoft Windows 上的一种常见字体，它也在 macOS 和 Linux 等其他平台上存在。这是一种无衬线字体，适合用于屏幕显示。
// Arial is a common font on Microsoft Windows and also exists on other platforms such as macOS and Linux. This is a sans serif font suitable for screen display.