/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230907
* @version:0.0.1
* @type:interface
* @description:
* # STag
* A small tag used to display data
* ## properties
* - in property <string> content : the content of the tag
* - in property <brush> font-color : tag font color
* - in property <length> font-size : tag font size
* ## functions
* see card's functions
* ## callbacks
* - callback clicked(string) : run if you click the tag
* ============================================
*/
import {ROOT_STYLES,DefaultSTagProps} from "../../themes/index.slint";
import { SText } from "../text/index.slint";
import { SCard } from "../card/index.slint";
import { Themes } from "../../use/index.slint";
export component Tag inherits SCard { 
  card-height: inner.height;
  card-width: inner.width;
  padding-type: text==""?None:Tag;
  border-radius: self.height / 2;
  font-color<=> inner.color;
  font-size:DefaultSTagProps.font-size;
  in property <string> text : DefaultSTagProps.text;
  callback clicked(string);
  inner:=SText{
    theme: root.theme;
    z:12;
    text: root.text;
    font-size: root.font-size;
    font-weight: root.font-weight;
    font-family: root.font-family;
    font-italic: root.font-italic;
  }
  TouchArea {
    z: 13;
    clicked => {
      root.clicked(root.text);
    }
  }
} 
 