import {SButton, SAlert} from "../../index.slint";
import {Themes,ResultType} from "../../themes/index.slint";

component TestAlert inherits Window {
  height: 400px;
  width: 600px;
  background: #535353;
 
  SButton {
    
    text: "show";
    clicked => {
      p.open();
      
      debug("sds1")
    }
  }
 

  p:=SAlert { 
    res-type:ResultType.Success ;
    content:"this is a success message!";
  }
}