import {SButton, SAlert} from "../../index.slint";
import {ResultType,Themes,UseIcons} from "../../use/index.slint";

component TestAlert inherits Window {
  height: 400px;
  width: 600px;
  background: #535353;
 
  SButton {
    text: "show";
    clicked => {
      p.open();
      
      debug("sds1")
    }
  }
 

  p:=SAlert { 
    
    icon :UseIcons.icons.Attention;
    res-type:ResultType.Success ;
    text:"this is a success long message .... long long long!";
  }
}