import {SURButton} from "/index.slint";
import {Themes,Icons} from "/themes/index.slint";
component TestWindow inherits Window {
  height: 400px;
  width: 400px;
  SURButton {
    x: 20px;
    y: 10px;
    
    theme:Themes.Dark;
    icon:Icons.Mini-sd-card;
    clicked => {
      self.content = "clicked"
    }
  }
  SURButton {
    x: 260px;
    y: 10px;

    content:"Save";
    clicked => {
      self.content = "clicked"
    }
  }
  SURButton {
    x: 20px;
    y: 100px;

    theme:Themes.Success;

  }
  SURButton {
    x: 20px;
    y: 200px;

    theme:Themes.Primary;
  }
  SURButton {
    x: 20px;
    y: 300px;
   
    theme:Themes.Info;
  }
  SURButton {
    x: 200px;
    y: 100px;
   
    theme:Themes.Error;
    icon:Icons.Magic-hat;
  }
  SURButton {
    x: 200px;
    y: 200px;
    
    theme:Themes.Warning;
  }
}