import {SURButton,SURCard,SURText} from "../../index.slint";
import {Themes,Icons} from "../../themes/index.slint";

component TestWindow inherits Window {
  height: 400px;
  width: 400px;
  background: #F5F5F5;
  
  SURCard { 
    y: 20px;
    card-width:text.width;
    text:=SURText {
      content: "SURCard";
    }
   }
   SURCard { 
    y: 80px;
    card-width:240px;
    card-height:120px;
    theme: Themes.Warning;
   }
   SURCard { 
    y: 240px;
    theme: Themes.Dark;
    card-width:240px;
    card-height:120px;
    border: X-Large;
   }
}