import {SDialog,SButton,STable,STableColumn} from "../../index.slint";
import {Themes} from "../../use/index.slint";

component TestDialog inherits Window {
  height: 600px;
  width: 600px;
  background: #535353;
 
  SButton {
    
    text: "show";
    clicked => {
      p.open();
    }
  }
 

  p:=SDialog {
    dialog-details : "";
    confirm-btn-theme: Success;
    dialog-width:80%;
    dialog-height:52%;
    dialog-title: "Surrealism Dialog Title";
    dialog-title-size: 20px;
    dialog-details-padding-top : 16px;
    // do after confirm btn clicked
    viewport-height : dialog-detail.height;
    // viewport-width : dialog-detail.width;
    confirm=>{
      debug("confirm btn clicked~!")
    }
    dialog-detail:=Rectangle {
      height: 200px;
      STable {
        // you can use this way to get height
        // it depends on how many datas in column
        height: tcol1.get-height();
        width: 350px;
        
        tcol1:=STableColumn {
          border:false;
          theme:Themes.Primary;
          width: 100px;
          name:"id";
          // row-height:60px;
          datas: ["101","102","103"];
        }
        STableColumn {
          theme:Themes.Primary;
          width: 100px;
          name:"name";
          datas: ["Mat","Jarry","Kaven"];
        }
        STableColumn {
          theme:Themes.Primary;
          width: 150px;
          name:"Operations";
          // cheat datas
          datas: [" "," "," "];
          operation-enabled:true;
        }
      }
    }
  }
}

