import {SURText,SURInput,SURButton, SURIcon,SURPopup} from "../../index.slint";
import {Themes} from "../../themes/index.slint";
import { TextEdit , LineEdit} from "std-widgets.slint";
import { Invoke } from "./invoke_input.slint";

export component TestInput inherits Window {
  height: 500px;
  width: 600px;
  p:=SURPopup {
    Invoke {}
  }
  SURInput{
    y: 20px;
    placeholder :"please enter your username";
    input-width:360px;
    accepted(res)=>{
      debug("content in input:" + res);
      p.open();
    }
    changed(change-res)=>{
      debug(change-res);
    }
    
  }
  // w:=SURInput{
  //   y: 80px;
  //   theme:Themes.Success;
  //   type:InputType.password;
  //   password:true;
  // }
  // SURInput{
  //   y: 140px;
  //   theme:Themes.Error;
  //   disabled:true;
  //   content:"disabled";
  // }
  // SURInput{
  //   y: 200px;
  //   theme:Themes.Dark;
  // }

  // SURInput{
  //   y: 260px;
  //   theme:Themes.Warning;
  //   clearable:true;
  // }
  // SURInput{
  //   y: 320px;
  //   theme:Themes.Info;
  //   type:InputType.password;
  //   clearable:true;
  //   password:true;
  // }
  
}