import { SMenu , SIcon, SButton} from "../../index.slint";
import {UseIcons} from "../../use/index.slint";

component TestMenu inherits Window {
    height: 600px;
    width: 300px;
    Rectangle {
      x: 1px;
      y: 0;
      height:parent.height;
      width: menu.width;
     
      menu:=SMenu {
        more-width :180px;
        theme: Dark;
        change(index,item)=>{
          debug(index);
          debug(item);
        }
      }
    }
}