import {SURPopup,SURButton} from "../../index.slint";
import {Themes} from "../../themes/index.slint";

component TestPopup inherits Window {
  height: 800px;
  width: 800px;
  background: #535353;
 
  SURButton {
    
    text: "show";
    clicked => {
      p.open();
      
      debug("sds1")
    }
  }
 

  p:=SURPopup {
    SURButton {
      text: "you can add anything in Popup";
      y: 160px;
    }
  }
}