import {SProgress,SButton} from "../../index.slint";
import {Themes} from "../../use/index.slint";

component TestDivider inherits Window {
  height: 400px;
  width: 400px;
  background: #5b64cd;
  SProgress {
    y: 100px;
    progress: 10;
  }
  a:=SProgress {
    y: 200px;
    progress: 32;
    theme:Primary;
  }
  SProgress {
    y: 300px;
    theme:Dark;
    progress:86;
  }
  SButton{
    x: 60px;
    y: 340px;
    text: "add";
    clicked => {
      a.add(5);
    }
  }
  SButton{
    x: 160px;
    y: 340px;
    text: "full";
    clicked => {
      a.full();
    }
  }
  SButton{
    x: 260px;
    y: 340px;
    text: "clear";
    clicked => {
      a.clear();
    }
  }
}