import {SSlider} from "../../index.slint";

component TestSlider inherits Window{
    height: 400px;
    width: 400px;
    VerticalLayout {
        spacing: 20px;
        padding: 20px;
        SSlider {
            theme: Light;
            width: 360px;
            height: 40px;
            stroke-width: 16px;
            progress: 0.3;
        }
        SSlider {
            width: 360px;
            height: 40px;
            progress: 80%;
        }

        SSlider {
            theme: Success;
            width: 30px;
            height: 220px;
            stroke-width: 220px;
            progress: 30%;
            orientation: Orientation.vertical;
        }
    }
}