import { SSwitchOption } from "../../index.slint";

component TestSwitchOption inherits Window {
  height: 400px;
  width: 400px;
  SSwitchOption {
    y: 30px;
    left:"surrealism";
    right:"slint";
    clicked(res) => {
      debug(res)
    }
  }
  SSwitchOption {
    y: 100px;
    theme: Primary;
    left:"surrealism";
    right:"slint";
  }
  SSwitchOption {
    y: 170px;
    theme: Dark;
    left:"surrealism";
    right:"slint";
  }
}