import { SURSwitch } from "../../index.slint";

component TestSwitch inherits Window {
  height: 400px;
  width: 400px;
  SURSwitch {
    y: 30px;
  }
  SURSwitch {
    theme: Primary;
    y: 80px;
    switch-background-color:#ddd;
    switch-border-color:#00ff00;
  }
  SURSwitch {
    y: 130px;
    theme: Dark;
    clicked(active-or-not)=>{
      debug(active-or-not);
    }
  }
  SURSwitch {
    y: 180px;
    theme: Warning;
  }
  SURSwitch {
    y: 230px;
    theme: Error;
  }
  SURSwitch {
    y: 280px;
    theme: Info;
  }
}