import {STable,STableColumn, SCard,STableColumnOperate} from "../../index.slint";
import {Themes,PaddingType,ShadowType,BorderType,PaddingProps,BorderProps,ShadowProps,UseSurrealismFn} from "../../use/index.slint";
import { ROOT-STYLES,DefaultSCardProps,ComponentSchema } from "../../themes/index.slint";
import { ScrollView } from "std-widgets.slint";


export component TestTable inherits Window {
  height: 500px;
  width: 600px;
  STable{
    theme: Dark;
    width: 90%;
    height: 36%;
    column-themes:[Themes.Primary,Themes.Dark,Themes.Error,Themes.Dark];
    viewport-height:col1.height;
    alignment: center;
    columns: [
      {label:"序号",value:"$index"},
      {label:"username",value:"name"},
      {label:"age",value:"age"},
      {label:"operate",value:"opt"},
    ];
    clicked(index,item)=>{
      debug(index);
      debug(item);
    }
    
    col1:=STableColumn {
      alignment: left;
      datas:[
        "1",
        "2",
        "3",
        "3",
        "3",
      ];
      width: parent.get-column-width(parent.width , 0);
    }
    STableColumn {
      index:1;
      width: parent.get-column-width(parent.width , 1);
      datas:[
        "Matt",
        "John",
        "Gary",
        "Harry",
        "Mary",
      ];
      clicked(col-index,index,value)=>{
        debug(col-index);
        debug(index);
        debug(value);
      }
    }
    STableColumn {
      index: 2;
      theme: Light;
      width: parent.get-column-width(parent.width , 2);
      datas:[
        "16",
        "12",
        "19",
        "21",
        "11",
      ];
    }
    STableColumnOperate {
      index: 3;
      theme: Dark;
      width: parent.get-column-width(parent.width , 3);
      len:5;
      // btns:[];
      // btns:[
      //   ComponentSchema.button,
      // ];
    }
    // STableColumn {
    //   index: 3;
    //   theme: Light;
    //   width: parent.get-column-width(parent.width , 3);
    //   datas:[
    //     "16",
    //     "12",
    //     "19",
    //     "21",
    //     "11",
    //   ];
    // }
  }
}