import {STable,STableColumn, SCard} from "../../index.slint";
import {Themes,PaddingType,ShadowType,BorderType,PaddingProps,BorderProps,ShadowProps,UseSurrealismFn} from "../../use/index.slint";
import { ROOT-STYLES,DefaultSCardProps } from "../../themes/index.slint";
import { ScrollView } from "std-widgets.slint";

export component TestTable inherits Window {
  height: 500px;
  width: 500px;
  STable{
    theme: Dark;
    width: 86%;
    height: 36%;
    column-themes:[Themes.Primary,Themes.Dark,Themes.Error];
    viewport-height:col1.height;
    alignment: center;
    columns: [
      {label:"序号",value:"$index"},
      {label:"username",value:"name"},
      {label:"age",value:"age"},
    ];
    clicked(index,item)=>{
      debug(index);
      debug(item);
    }
    
    col1:=STableColumn {
      alignment: left;
      datas:[
        "1",
        "2",
        "3",
        "3",
        "3",
      ];
      width: parent.get-column-width(parent.width , 0);
    }
    STableColumn {
      index:1;
      width: parent.get-column-width(parent.width , 1);
      datas:[
        "Matt",
        "John",
        "Gary",
        "Harry",
        "Mary",
      ];
      clicked(col-index,index,value)=>{
        debug(col-index);
        debug(index);
        debug(value);
      }
    }
    STableColumn {
      theme: Light;
      width: parent.get-column-width(parent.width , 2);
      datas:[
        "16",
        "12",
        "19",
        "21",
        "11",
      ];
    }
  }
}