import {STag} from "../../index.slint";
import {Themes} from "../../use/index.slint";

component TestWindow inherits Window {
  height: 400px;
  width: 400px;
  STag {
    text:"default";
    y: 40px;
  }
  STag {
    text:"error!";
    y:80px;
    theme:Themes.Error;
  }
  STag {
    text:"callback";
    y:120px;
    theme:Themes.Dark;
    clicked(text)=>{
      self.font-color= #ddff00;
    }
  }
  STag {
    text:"success";
    y:160px;
   
    theme:Themes.Success;
  }
}