import {STip,SButton } from "../../index.slint";
import {Themes} from "../../use/index.slint";


component TestWindow inherits Window {
  height: 400px;
  width: 400px;
  STip{
    y: 80px;
     height:inner0.height;
     width: inner0.width;
     theme: Dark;
     pos:Top;
     text:"this is a \n........tip window";
     show-tip:inner0.has-hover;
     inner0:=SButton { 
       text: "hover";
     }
   }
  STip{
    height:inner.height;
    width: inner.width;
    theme: Dark;
    pos:Left;
    text:"this is a \n........tip window";
    inner:=SButton { 
      text: "click";
      clicked => {
        parent.clicked();
      }
    }
  }
  STip{
   y: 300px;
    height:inner2.height;
    width: inner2.width;
    theme: Dark;
    pos:Top;
    text:"this is a \n........tip window";
    inner2:=SButton { 
      text: "click";
      clicked => {
        parent.clicked();
      }
    }
  }
 
}