/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230905
* @version:0.0.1
* @type:interface
* @description:Struct for Theme Font
* ============================================
*/

struct ThemeFont {
    font-family:string,
    font-weight:int,
    font-size:length,
    font-italic:bool,
    letter-spacing:length,
    tag-size:length
}

export { ThemeFont }