import {Icons} from "../../themes/src/icon.slint";

struct IconItem {
  name:Icons,
  icon:image
}

global IconSources {
    out property <Icons> icons : {
      Null:@image-url(""),
      Loading:@image-url("../../icons/loading.svg"),
      Avatar:@image-url("../../icons/avatar.svg"),
      Success:@image-url("../../icons/success.svg"),
      Smiling_face:@image-url("../../icons/smiling-face.svg"),
      Info:@image-url("../../icons/info.svg"),
      Close_one:@image-url("../../icons/close-one.svg"),
      Attention:@image-url("../../icons/attention.svg"),
      Help:@image-url("../../icons/help.svg"),
      Share:@image-url("../../icons/share.svg"),
      Up:@image-url("../../icons/up.svg"),
      Down:@image-url("../../icons/down.svg"),
      Down_one:@image-url("../../icons/down-one.svg"),
      Right_one:@image-url("../../icons/right-one.svg"),
      Link_left:@image-url("../../icons/link-left.svg"),
      Preview_close:@image-url("../../icons/preview-close.svg"),
      Preview_open:@image-url("../../icons/preview-open.svg"),
      Close_one:@image-url("../../icons/close-one.svg"),
      Setting_two:@image-url("../../icons/setting-two.svg"),
      Folder:@image-url("../../icons/folder-open.svg"),
      Folder_filled:@image-url("../../icons/folder-open-filled.svg"),
      FileCode:@image-url("../../icons/file-code.svg")
    };
}

export { IconItem,IconSources }