/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230912
* @version:0.1.1
* @type:interface
* @description:
* # SURRadio
* A masked pop-up layer appears in the current window
* And users will not be able to use the pop-up layer to cover the components under it. 
* Clicking on the pop-up layer again will close it
* ## properties
* - in-out property <bool> is-show : the popup layer is show or not
* - in property <Themes> theme : Surrealism Themes
* ## functions
* ## callbacks
* - callback open() : open the popup
* - callback close() : close the popup
* ============================================
*/

export component Radio inherits Rectangle {
    
}