/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230910
* @version:0.1.0
* @type:interface
* @description:
* # SURLink
* SURLink is commonly used to represent text connections or sharing
* ## properties
* - in property <image> icon : share icon you can use whatever you want
* - in property <bool> funny : Easter egg just funny
* - in property <bool> underline : has underline
* - out property <bool> has-hover : link has been hover or not
* - in property <MouseCursor> mouse-cursor : mouse cursor
* - in property <Themes> theme : Surrealism Theme
* - in property <length> font-size : link font size
* - in-out property <string> text : link text
* - private property <brush> text-color : text color⛔
* ## callbacks
* - callback clicked(string) : run if you click share icon
* ============================================
*/

import { SURText } from "../text/index.slint";
import { SURCard } from "../card/index.slint";
import {Shadows} from "../../themes/index.slint";
import { SURIcon } from "../icon/index.slint";
import { IconSources,Themes,ROOT-STYLES,ColorLevel } from "../../themes/index.slint";
export component Link {
  callback clicked(string);
  in property <image> icon : IconSources.icons.Share;
  in property <bool> funny : false;
  in property <bool> underline : true;
  out property <bool> has-hover <=> touch-area.has-hover;
  in property <MouseCursor> mouse-cursor;
  in property <Themes> theme : Light;
  in property <length> font-size : ROOT-STYLES.sur-font.font-size;
  in-out property <string> text<=>inner-text.text;
  private property <brush> text-color;
  states [
    hover when touch-area.has-hover: {
      inner-text.color : ROOT-STYLES.deeper(root.theme,ROOT-STYLES.get-color(root.theme,ColorLevel.Font));
      link-icon.icon-color : ROOT-STYLES.deeper(root.theme,ROOT-STYLES.get-color(root.theme,ColorLevel.Font)); 
    }
  ]
  touch-area:=TouchArea {
    z: 14;
    mouse-cursor: pointer;
    clicked => {
      root.clicked(root.text)
    }
    if touch-area.has-hover&&underline: SURCard {
      y: root.height;
      height: 1px;
      width: root.width;
      theme: root.theme;
      padding-left: 0;
      padding-right: 0;
      padding-top: 0;
      padding-bottom: 0;
      border: root.funny? Circle-None: None;
    }
    HorizontalLayout {
      inner-text:=SURText{
        theme: root.theme;
        font-size: root.font-size;
      }
      Rectangle {
        height: link-icon.width;
        width: link-icon.width + self.padding-left;
        padding-left: 2px;
        link-icon:=SURIcon{
          x: 2px;
          source: root.icon;
          theme: root.theme;
          height: root.font-size / 1.4;
          width: root.font-size / 1.4;
        }
      }
    }
  }
}
