import { Themes } from "./theme.slint";
import { PaddingType } from "./padding.slint";
import { ShadowType } from "./shadow.slint";
import { BorderType } from "./border.slint";

export struct SButtonProps {
  font-weight : int,
  font-size : length,
  color : brush,
  font-italic : bool,
  font-family : string,
  theme : Themes,
  padding-type : PaddingType,
  shadow-type : ShadowType,
  border-type : BorderType,
  icon : image,
  show-icon : bool,
  text : string,
  letter-spacing : length,
  clip : bool,
  round : bool,
  disabled: bool,
}