import { Themes } from "./theme.slint";

export enum KeyBoardType {
    PhoneAlpha,
    PhoneNumber,
    Computer,
}


export enum KeyItems{
    // .
    Point,
    // /
    Div,
    // +
    Add,
    // -
    Sub,
    // *
    Mul,
    // @
    At,
    // &
    And,
    // %
    Percent,
    // $
    Dollar,
    // !
    Exclamation,
    // ⎵
    Space,
    // ⌫
    Back,
    // ⏎
    Enter,
    // =
    Equal,
    // ?
    Question,
    // ,
    Comma,
    // 0
    Zero,
    // 1
    One,
    // 2
    Two,
    // 3
    Three,
    // 4
    Four,
    // 5
    Five,
    // 6
    Six,
    // 7
    Seven,
    // 8
    Eight,
    // 9
    Nine,
    // A
    A,
    // B
    B,
    // C
    C,
    // D
    D,
    // E
    E,
    // F
    F,
    // G
    G,
    // H
    H,
    // I
    I,
    // J
    J,
    // K
    K,
    // L
    L,
    // M
    M,
    // N
    N,
    // O
    O,
    // P
    P,
    // Q
    Q,
    // R
    R,
    // S
    S,
    // T
    T,
    // U
    U,
    // V
    V,
    // W
    W,
    // X
    X,
    // Y
    Y,
    // Z
    Z,
    // `
    BackQuote,
    // ~
    Tilde,
    // ^
    Caret,
    // (
    LeftParenthesis,
    // )
    RightParenthesis,
    // {
    LeftBrace,
    // }
    RightBrace,
    // [
    LeftBracket,
    // ]
    RightBracket,
    // <
    Less,
    // >
    Greater,
    // :
    Colon,
    // ;
    Semicolon,
    // '
    SingleQuote,
    // "
    DoubleQuote,
    // |
    Pipe,
    // \
    Slash,
    // _
    Underline,
    // '
    Apostrophe,
    // #
    Hash,
 }

 export struct SKeyItem {
    label: string,
    value: KeyItems
}

export struct SKeyBoardProps {
    theme: Themes,
    font-size:length,
    keyboard-type: KeyBoardType,
}