import { Themes } from "./theme.slint";

export enum BarType{
  Vertical,
  Horizontal,
  Circle
}

export struct SProgressProps {
  //font
  font-weight : int,
  font-size: length,
  font-color : brush,
  font-italic : bool,
  font-family : string,
  //theme
  theme : Themes,
  //hight-width
  height : length,
  width : length,
  text : string,
  progress : float,
  stroke-width: length,
  stroke-color: brush,
  bar-type: BarType,
}