import { Themes } from "./theme.slint";

/**文字类型属性 */
struct FontProps {
  font-family : string,
  font-size : length,
  font-weight : int,
  font-italic : bool,
  color : brush
}

/**文字对齐属性 */
struct TextAlignmentProps {
  horizontal-alignment : TextHorizontalAlignment,
  vertical-alignment : TextVerticalAlignment,
}

/**行为属性 */
struct TextActionProps {
  wrap : TextWrap,
  overflow : TextOverflow,
  letter-spacing : length,
}

struct STextProps {
  font-family : string,
  font-weight : int,
  font-size : length,
  color : brush,
  font-italic : bool,
  theme : Themes,
  wrap :TextWrap,
  overflow : TextOverflow,
  letter-spacing : length,
  horizontal-alignment : TextHorizontalAlignment,
  vertical-alignment : TextVerticalAlignment,
}

export { FontProps, TextAlignmentProps, TextActionProps,STextProps }