/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230223
* @version:0.3.0
* @type:interface
* @description: surrealism中所有组件所需的外置化类型
* ============================================
*/


/**Surrealism-UI主题枚举 */
export enum Themes{
  Light,
  Primary,
  Success,
  Info,
  Warning,
  Error,
  Dark
}

// import {FontProps,TextActionProps,TextAlignmentProps} from "./text.slint";
// import {BorderType,BorderProps,ThemeBorder} from "./border.slint";
// import {PaddingType,PaddingProps,ThemePadding} from "./padding.slint";
// import {ShadowType} from "./shadow.slint";

// export { 
//   FontProps,TextActionProps,TextAlignmentProps,BorderType,BorderProps,ThemeBorder,
//   PaddingType,PaddingProps,ThemePadding,ShadowType
// }

