import { SIcon } from "../icon/index.slint";
export component Carousel{
    in property <[image]> sources;
    in property <float> fold-strench: 1.1;
    in property <length> fold-width: 42px;
    in property <length> fold-height: root.height;
    in property <ImageFit> fit: ImageFit.preserve;
    in property <bool> focus-main: false;
    in-out property <int> active: 0;
    callback clicked(int);
    layout:= HorizontalLayout {
        alignment: LayoutAlignment.center;
        spacing: 16px;
        for source[index] in root.sources: source-wrap := Rectangle {
            width: root.active == index ? root.width - (sources.length * fold-width) - (layout.spacing * 2) : fold-width;
            clip: true;
            animate width {
                duration: 800ms;
                easing: ease-in-out-quint;
            }
            Rectangle {
                height: root.active == index ? root.fold-height :  root.fold-height / ( Math.abs(index - sources.length / 2) / 10 + fold-strench);
                border-radius: root.active == index ? 0 : fold-width / 2;
                clip: true;
                animate border-radius, height {
                    duration: 800ms;
                    easing: ease-in-out-quint;
                }

                SIcon {
                    height: root.height;
                    width: 100%;
                    source: source;
                    image-fit: root.fit;
                    clicked => {
                        root.active = index;
                        root.clicked(root.active);
                    }
                }
            }
        }
    }
}

component TestCarousel {
    height: 400px;
    width: 600px;
    Rectangle {
        Carousel {
            height: 300px;
            width: 100%;
            active: 2;
            sources: [
                @image-url("../../README/imgs/sed1.jpeg"),
                @image-url("../../README/imgs/sed2.jpeg"),
                @image-url("../../README/imgs/sed3.png"),
                @image-url("../../README/imgs/sed4.png"),
                @image-url("../../README/imgs/sed5.png")
            ];
        }
    }
}