/**surrealism-use-export*/
import {Themes} from "./src/theme.slint";
import {ThemePadding,PaddingType,PaddingProps} from "./src/padding.slint";
import {FontProps, TextAlignmentProps, TextActionProps} from "./src/text.slint";
import { BorderType,BorderProps,ThemeBorder } from "./src/border.slint";
import { ShadowType,ShadowProps,ThemeShadow } from "./src/shadow.slint";
import {ThemeColor,ColorLevel,ColorProps} from "./src/color.slint";
import {ResultType} from "./src/result.slint";
import {ThemeSpace} from "./src/spacing.slint";
import {Size,SizeProps} from "./src/size.slint";
import {CommonPosition} from "./src/position.slint";
// import {ROOT-STYLES} from "../themes/src/index.slint";
import {UseSurrealismFn} from "./src/fn.slint";

export { 
  ThemePadding,
  PaddingType,
  PaddingProps,
  FontProps, 
  TextAlignmentProps, 
  TextActionProps,
  BorderType,
  BorderProps,
  ThemeBorder,
  ThemeColor,
  ColorLevel,
  ColorProps,
  ShadowType,
  ShadowProps,
  ThemeShadow,
  ResultType,
  ThemeSpace,
  Size,
  SizeProps,
  CommonPosition,
  Themes,
  UseSurrealismFn
}

