/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230910
* @version:0.1.0
* @type:interface
* @description:
* # SURAvatar
* SURAvatar is a avatar component that defaults to Icons.Avatar when there are no images available
* ## properties
* - in property <length> avatar-size : avatar size
* - in property <image> avatar : avatar image
* ============================================
*/
import { SCard } from "../card/index.slint";
import { SIcon } from "../icon/index.slint";
import {ROOT_STYLES,IconSources} from "../../themes/index.slint";
import { Themes,PaddingType,PaddingProps,ShadowType,BorderType,BorderProps,UseSurrealismFn } from "../../use/index.slint";

export component Avatar inherits SCard { 
  border-type:Circle-Normal;
  // padding: self.card-padding.padding-same;
  card-height:avatar-size;
  card-width:avatar-size;
  in property <length> avatar-size : ROOT-STYLES.sur-size.normal * 2;
  in property <image> avatar;
  padding-type: Normal;
  clip: true;
  init => {
    self.card-padding = UseSurrealismFn.get-padding(self.padding-type);
    self.padding = self.card-padding.padding-same;
    self.padding-top = self.card-padding.padding-same;
    self.padding-bottom = self.card-padding.padding-same;
    self.padding-left = self.card-padding.padding-same;
    self.padding-right = self.card-padding.padding-same;
  }
  SIcon {
    z: 13;
    height: avatar-size;
    width: avatar-size;
    source: IconSources.icons.Avatar;
    theme: root.theme;
  }
  Image {
    z: 15;
    height: root.height;
    width: root.width;
    source: avatar;
    image-fit: ImageFit.cover;
  }
}