import { DefaultSTextProps } from "./text.slint";
import { DefaultSButtonProps } from "./button.slint";
import { DefaultSPersonaProps } from "./persona.slint";
import { DefaultSLinkProps } from "./link.slint";
import { DefaultSCardProps } from "./card.slint";
import { DefaultSIconProps } from "./icon.slint";
import { DefaultSTagProps } from "./tag.slint";
import { DefaultSResultProps } from "./result.slint";
import { DefaultSAlertProps } from "./alert.slint";
import { DefaultSSwitchProps } from "./switch.slint";
import { DefaultSRadioProps } from "./radio.slint";
import { DefaultSAvatarProps } from "./avatar.slint";
import { DefaultSDividerProps } from "./divider.slint";
import { 
  SButtonProps,STextProps,SPersonaProps,SLinkProps,SCardProps,SIconProps,
  STagProps,SResultProps,SAlertProps,SSwitchProps,SRadioProps,SAvatarProps,
  SDividerProps
} from "../../use/index.slint";

export global ComponentSchema {
  //component props 
  in-out property <SCardProps> card : {
    font-weight : DefaultSCardProps.font-weight,
    font-size: DefaultSCardProps.font-size,
    color : DefaultSCardProps.color,
    font-italic : DefaultSCardProps.font-italic,
    font-family : DefaultSCardProps.font-family,
    //theme
    theme : DefaultSCardProps.theme,
    //hight-width
    card-height : DefaultSCardProps.card-height,
    card-width : DefaultSCardProps.card-width,
    padding-type: DefaultSCardProps.padding-type,
    shadow-type: DefaultSCardProps.shadow-type,
    border-type : DefaultSCardProps.border-type,
    clip : DefaultSCardProps.clip,
  };
  in-out property <SButtonProps> button : {
    font-weight : DefaultSButtonProps.font-weight,
    font-size : DefaultSButtonProps.font-size,
    color : DefaultSButtonProps.color,
    font-italic : DefaultSButtonProps.font-italic,
    font-family : DefaultSButtonProps.font-family,
    theme : DefaultSButtonProps.theme,
    padding-type : DefaultSButtonProps.padding-type,
    shadow-type : DefaultSButtonProps.shadow-type,
    border-type : DefaultSButtonProps.border-type,
    icon : DefaultSButtonProps.icon,
    show-icon : DefaultSButtonProps.show-icon,
    text : DefaultSButtonProps.text,
    letter-spacing : DefaultSButtonProps.letter-spacing,
    clip :DefaultSButtonProps.clip,
    round : DefaultSButtonProps.round
  };
  in-out property <STextProps> text : {
    font-family : DefaultSTextProps.font-family,
    font-weight : DefaultSTextProps.font-weight,
    font-size : DefaultSTextProps.font-size,
    color : DefaultSTextProps.color,
    font-italic : DefaultSTextProps.font-italic,
    theme : DefaultSTextProps.theme,
    wrap :DefaultSTextProps.wrap,
    overflow : DefaultSTextProps.overflow,
    letter-spacing :DefaultSTextProps.letter-spacing,
    horizontal-alignment : DefaultSTextProps.horizontal-alignment,
    vertical-alignment : DefaultSTextProps.vertical-alignment,
  };
  in-out property <SIconProps> icon : {
    theme : DefaultSIconProps.theme,
    height : DefaultSIconProps.height,
    width : DefaultSIconProps.width,
    padding : DefaultSIconProps.padding,
    //image props
    source : DefaultSIconProps.source,
    colorize : DefaultSIconProps.colorize,
    image-fit : DefaultSIconProps.image-fit,
    image-rendering : DefaultSIconProps.image-rendering,
    rotation : DefaultSIconProps.rotation,
    source-clip-x : DefaultSIconProps.source-clip-x,
    source-clip-y : DefaultSIconProps.source-clip-y,
    source-clip-height : DefaultSIconProps.source-clip-height,
    source-clip-width : DefaultSIconProps.source-clip-width
  };
  in-out property <SLinkProps> link : {
    icon : DefaultSLinkProps.icon,
    funny :  DefaultSLinkProps.funny,
    underline : DefaultSLinkProps.underline,
    mouse-cursor : DefaultSLinkProps.mouse-cursor,
    theme : DefaultSLinkProps.theme,
    font-size : DefaultSLinkProps.font-size,
    text: DefaultSLinkProps.text,
    font-weight : DefaultSLinkProps.font-weight,
    font-family : DefaultSLinkProps.font-family,
    font-italic : DefaultSLinkProps.font-italic,
  };
  in-out property <STagProps> tag : {
    text : DefaultSTagProps.text,
    font-size : DefaultSTagProps.font-size,
    font-weight : DefaultSTagProps.font-weight,
    font-family : DefaultSTagProps.font-family,
    font-italic : DefaultSTagProps.font-italic,
    theme : DefaultSTagProps.theme,
    padding-type : DefaultSTagProps.padding-type,
    border-type : DefaultSTagProps.border-type,
    shadow-type : DefaultSTagProps.shadow-type
  };
  in-out property <SPersonaProps> persona : {
    btn-text : DefaultSPersonaProps.btn-text,
    btns : DefaultSPersonaProps.btns,
    //avatar
    avatar : DefaultSPersonaProps.avatar,
    avatar-height: DefaultSPersonaProps.avatar-height,
    avatar-theme : DefaultSPersonaProps.avatar-theme,
    card-width : DefaultSPersonaProps.card-width,
    spacing : DefaultSPersonaProps.spacing,
    //name
    name : DefaultSPersonaProps.name,
    name-height: DefaultSPersonaProps.name-height,
    name-font-size: DefaultSPersonaProps.name-font-size,
    name-font-weight : DefaultSPersonaProps.name-font-weight,
    name-theme: DefaultSPersonaProps.name-theme,
    name-font-family: DefaultSPersonaProps.name-font-family,
    name-font-italic: DefaultSPersonaProps.name-font-italic,
    //des
    des : DefaultSPersonaProps.des,
    des-height: DefaultSPersonaProps.des-height,
    des-font-size: DefaultSPersonaProps.des-font-size,
    des-font-weight : DefaultSPersonaProps.des-font-weight,
    des-theme: DefaultSPersonaProps.des-theme,
    des-font-family: DefaultSPersonaProps.des-font-family,
    des-font-italic: DefaultSPersonaProps.des-font-italic,
  };
  in-out property <SResultProps> result : {
    card-height : DefaultSResultProps.card-height,
    card-width : DefaultSResultProps.card-width,
    icon-size : DefaultSResultProps.icon-size,
    btns :DefaultSResultProps.btns,
    btn-text : DefaultSResultProps.btn-text,
    result-type: DefaultSResultProps.result-type,
    text : DefaultSResultProps.text,
    padding-type: DefaultSResultProps.padding-type,
    shadow-type: DefaultSResultProps.shadow-type,
    border-type : DefaultSResultProps.border-type,
    icon : DefaultSResultProps.icon,
    theme : DefaultSResultProps.theme,
  };
  in-out property <SAlertProps> alert : {
    font-weight : DefaultSAlertProps.font-weight,
    font-size:  DefaultSAlertProps.font-size,
    color : DefaultSAlertProps.color,
    font-italic : DefaultSAlertProps.font-italic,
    font-family : DefaultSAlertProps.font-family,
    overflow : DefaultSAlertProps.overflow,
    spacing : DefaultSAlertProps.spacing,
    text : DefaultSAlertProps.text,
    is-show : DefaultSAlertProps.is-show,
    alert-height : DefaultSAlertProps.alert-height,
    result-type: DefaultSAlertProps.result-type,
    close-icon : DefaultSAlertProps.close-icon,
    icon-size : DefaultSAlertProps.icon-size,
  };
  in-out property <SSwitchProps> switch : {
    card-height : DefaultSSwitchProps.card-height,
    card-width : DefaultSSwitchProps.card-width,
    padding-type: DefaultSSwitchProps.padding-type,
    shadow-type: DefaultSSwitchProps.shadow-type,
    border-type : DefaultSSwitchProps.border-type,
    active : DefaultSSwitchProps.active,
    theme: DefaultSSwitchProps.theme,
    //switch-circle
    switch-height : DefaultSSwitchProps.switch-height,
    switch-width : DefaultSSwitchProps.switch-width,
    switch-padding-type: DefaultSSwitchProps.switch-padding-type,
    switch-shadow-type: DefaultSSwitchProps.switch-shadow-type,
    switch-border-type : DefaultSSwitchProps.switch-border-type,
    switch-background-color : DefaultSSwitchProps.switch-background-color,
    switch-border-color : DefaultSSwitchProps.switch-border-color,
    switch-drop-shadow-color : DefaultSSwitchProps.switch-drop-shadow-color,
  };
  in-out property <SRadioProps> radio : {
    font-weight : DefaultSRadioProps.font-weight,
    font-size: DefaultSRadioProps.font-size,
    color : DefaultSRadioProps.color,
    font-italic : DefaultSRadioProps.font-italic,
    font-family : DefaultSRadioProps.font-family,
    card-height : DefaultSRadioProps.card-height,
    card-width : DefaultSRadioProps.card-width,
    theme : DefaultSRadioProps.theme,
    active-color: DefaultSRadioProps.active-color,
    padding-type: DefaultSRadioProps.padding-type,
    shadow-type: DefaultSRadioProps.shadow-type,
    border-type : DefaultSRadioProps.border-type,
    text : DefaultSRadioProps.text,
    value : DefaultSRadioProps.value,
    actived : DefaultSRadioProps.actived,
  };
  in-out property <SAvatarProps> avatar : {
    card-height : DefaultSAvatarProps.card-height,
    card-width : DefaultSAvatarProps.card-width,
    padding-type: DefaultSAvatarProps.padding-type,
    shadow-type: DefaultSAvatarProps.shadow-type,
    border-type : DefaultSAvatarProps.border-type,
    avatar-size : DefaultSAvatarProps.avatar-size,
    avatar : DefaultSAvatarProps.avatar,
    alt : DefaultSAvatarProps.alt,
    image-fit : DefaultSAvatarProps.image-fit,
  };
  in-out property <SDividerProps> divider : {
    theme : DefaultSDividerProps.theme,
    height : DefaultSDividerProps.height,
    width : DefaultSDividerProps.width,
    padding-type: DefaultSDividerProps.padding-type,
    shadow-type: DefaultSDividerProps.shadow-type,
    border-type : DefaultSDividerProps.border-type,
  };
}