/**
* ============================================
* @author:syf20020816@outlook.com
* @since:20230907
* @version:0.0.1
* @type:interface
* @description:
* # SCollapse
* SCollapse is a foldable panel
* This is the outter of the Collapse, what really works is SCollapseItem
* The outter only serves as a standard layout , this is a zero cost construction
* ## properties inherits Rectangle
* ============================================
*/

import { Themes } from "../../use/index.slint";

export component Collapse inherits Rectangle { 
  clip: false;
  VerticalLayout {
    spacing: 0px;
    width: root.width;
    height: root.height;
    @children
  }
} 